name: Create base image

on:
  push:
    branches: main
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: base
          push: true
          platforms: arm64
          tags: ${{ env.docker_image }}
