name: Add extra stuff

on:
  push:
    branches: main
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Increment tag
        id: inc_tag
        run: echo ::set-output name=tag::$(( $(git describe --tags --abbrev=0) + 1))

      - name: Tag code
        run: |
          git tag ${{ steps.inc_tag.outputs.tag }} $(git rev-parse HEAD)
          git push origin ${{ steps.inc_tag.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: arm64
          tags: hex-developer/main:latest
