name: Create final image

on:
  push:
    branches: main
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Build docker image
        run: docker buildx build --platform linux/arm64 -t jetson-nano-image post/

      - name: Export rootfs
        run: |
          docker export $(docker create --name nano-rootfs --platform linux/arm64 jetson-nano-image) -o rootfs.tar
          docker rm nano-rootfs
          mkdir -p /tmp/jetson-builder/rootfs
          sudo tar --same-owner -xf rootfs.tar -C /tmp/jetson-builder/rootfs
          
      - name: Create jetson.img
        run: |
          sudo apt install -y libxml2-utils
          sudo -E ./create-image.sh
          tar -cJf jetson.tar.xz jetson.img
          
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.sha1 }}
          tag_name: ${{ steps.inc_tag.outputs.tag }}
          body: ""
        env: 
          GITHUB_TOKEN: ${{ github.token }}

          
      - name: Upload image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jetson.tar.xz
          asset_name: jetson.tar.xz
          asset_content_type: application/zip
